"""
This file will contain the code to decode the bytes generated by TsSegmentsFetcher
"""

import av
import io
import queue
from typing import Any

import numpy as np

from src.hls_player.models.models import (
    VideoPacket,
    AudioPacket,
)
from src.hls_player.models.models import DownloadedSegment
from src.hls_player.utils.loggers import get_logger

logger = get_logger(__name__)


class DecodeBytes:
    """
    This class contains the code to decode the bytes generated by TsSegmentsFetcher
    """

    def __init__(self) -> None:
        """
        This is a constructor for the DecodeBytes class
        """

        self.audio_queue = queue.Queue()
        self.video_queue = queue.Queue()

    @staticmethod
    def get_container_for_the_byte(downloaded_segment: DownloadedSegment) -> av.container.InputContainer:
        """
        This method will return the container of a byte

        :param downloaded_segment: one downloaded segment
        :return: container
        """

        return av.open(io.BytesIO(downloaded_segment.data))

    def generate_audio_and_video_packet_from_a_frame(self, frame: Any, discontinuity: bool = False) -> None:
        """
        This method will segregate the Audio and Video Packet from a decoded frame
        and will generate Models.VideoPacket and Models.AudioPacket and push them
        into their respective queues.

        :param frame: av.VideoFrame or av.AudioFrame
        :param discontinuity: True only for the first audio/video frame of a discontinuous segment
        :return: None
        """

        if isinstance(frame, av.VideoFrame):
            rgb_array = frame.to_ndarray(format='rgb24')
            pts = float(frame.pts * frame.time_base)
            video_packet = VideoPacket(
                rgb_array=rgb_array,
                pts=pts,
                discontinuity=discontinuity,
            )
            self.video_queue.put(video_packet)

        elif isinstance(frame, av.AudioFrame):
            pcm = frame.to_ndarray()
            if pcm.dtype != np.float32:
                if np.issubdtype(pcm.dtype, np.integer):
                    max_val = float(np.iinfo(pcm.dtype).max)
                else:
                    peak = np.abs(pcm).max()
                    max_val = float(peak) if peak > 1.0 else 1.0
                pcm = pcm.astype(np.float32) / max_val
            pts = float(frame.pts * frame.time_base)
            audio_packet = AudioPacket(
                pcm=pcm,
                pts=pts,
                sample_rate=frame.sample_rate,
                discontinuity=discontinuity,
            )
            self.audio_queue.put(audio_packet)

    def generate_audio_and_video_queue(self, downloaded_seg_que: queue.Queue) -> None:
        """
        This method will get one DownloadedSegment object from the TsSegmentsFetcher.downloaded_segment_que

        :param downloaded_seg_que: downloaded_segment_que
        :return: None
        """

        logger.debug("Starting to decode the downloaded segments (Bytes).")
        while True:
            downloaded_seg = downloaded_seg_que.get()
            if downloaded_seg is None:
                self.video_queue.put(None)
                self.audio_queue.put(None)
                logger.debug("All the downloaded segments has been decoded.")
                return
            logger.debug(f"Decoding segment [{downloaded_seg.sequence}]")

            seg_container = None
            try:
                seg_container = self.get_container_for_the_byte(downloaded_seg)
                first_audio_emitted = False
                first_video_emitted = False
                for packet in seg_container.demux():
                    for frame in packet.decode():
                        if frame.pts is None:
                            continue
                        if isinstance(frame, av.VideoFrame):
                            disc = downloaded_seg.discontinuity and not first_video_emitted
                            first_video_emitted = True
                        elif isinstance(frame, av.AudioFrame):
                            disc = downloaded_seg.discontinuity and not first_audio_emitted
                            first_audio_emitted = True
                        else:
                            disc = False
                        self.generate_audio_and_video_packet_from_a_frame(frame, discontinuity=disc)
            except av.FFmpegError as e:
                logger.error(f"Failed to decode segment {downloaded_seg.sequence}: {e}, skipping.")
            finally:
                if seg_container:
                    seg_container.close()
