"""
This file will contain the code to decode the bytes generated by TsSegmentsFetcher
"""

from typing import Any
import av
import io
import queue

from src.hls_player.models.models import (
    VideoPacket,
    AudioPacket,
)
from src.hls_player.models.models import DownloadedSegment
from src.hls_player.utils.loggers import get_logger

logger = get_logger(__name__)


class DecodeBytes:
    """
    This class contains the code to decode the bytes generated by TsSegmentsFetcher
    """

    def __init__(self) -> None:
        """
        This is a constructor for the DecodeBytes class
        """

        self.audio_queue = queue.Queue()
        self.video_queue = queue.Queue()

    @staticmethod
    def get_container_for_the_byte(downloaded_segment: DownloadedSegment) -> av.container.InputContainer:
        """
        This method will return the container of a byte

        :param downloaded_segment: one downloaded segment
        :return: container
        """

        return av.open(io.BytesIO(downloaded_segment.data))

    def generate_audio_and_video_packet_from_a_frame(self, frame: Any) -> None:
        """
        This method will segregate the Audio and Video Packet from a decoded frame
        and will generate Models.VideoPacket and Models.AudioPacket and push them
        into their respective queues.

        :param frame: av.VideoFrame or av.AudioFrame
        :return: None
        """

        if frame.stream.type == 'video':
            rgb_array = frame.to_ndarray(format='rgb24')
            pts = float(frame.pts * frame.time_base)
            video_packet = VideoPacket(
                rgb_array=rgb_array,
                pts=pts,
            )
            self.video_queue.put(video_packet)

        elif frame.stream.type == 'audio':
            pcm = frame.to_ndarray()
            pts = float(frame.pts * frame.time_base)
            audio_packet = AudioPacket(
                pcm=pcm,
                pts=pts,
                sample_rate=frame.sample_rate,
            )
            self.audio_queue.put(audio_packet)

    def generate_audio_and_video_queue(self, downloaded_seg_que: queue.Queue) -> None:
        """
        This method will get one DownloadedSegment object from the TsSegmentsFetcher.downloaded_segment_que

        :param downloaded_seg_que: downloaded_segment_que
        :return: None
        """

        logger.info("Starting to decode the downloaded segments (Bytes).")
        while True:
            downloaded_seg = downloaded_seg_que.get()
            if downloaded_seg is None:
                logger.info("All the downloaded segments has been decoded.")
                return

            seg_container = self.get_container_for_the_byte(downloaded_seg)
            for packet in seg_container.demux():
                if packet.pts is None:
                    continue

                for frame in packet.decode():
                    self.generate_audio_and_video_packet_from_a_frame(frame)
